services:
  api:
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
    networks:
      - librechat_network
  mongodb:
    networks:
      - librechat_network
  meilisearch:
    networks:
      - librechat_network
  clickhouse:
    image: clickhouse/clickhouse-server:25.4.2.31-alpine
    container_name: clickhouse_server
    restart: unless-stopped
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
    networks:
      - librechat_network
networks:
  librechat_network:
    driver: bridge